"""Predefined exercise metadata and form choices."""

from __future__ import annotations

from tracker.reports import BODY_PART_ORDER

EXERCISE_GROUPS = {
    "Chest": [
        "Barbell Bench Press",
        "Dumbbell Bench Press",
        "Dumbbell Pec Fly",
        "Pec Fly",
        "Push Up",
        "Vertical Chest Press Machine",
    ],
    "Back": [
        "45 Degree T Bar Row",
        "Assisted Pull Up",
        "Back Extension",
        "Barbell Romanian Deadlift",
        "Chest Supported Rows",
        "Compound Row Machine",
        "Dumbbell Rows",
        "Dumbbell Romanian Deadlift",
        "Lat Pull Down",
        "Pull Up",
        "Seated Cable Row",
        "Single Arm Dumbbell Row",
        "Straight Arm Cable Pulldown",
    ],
    "Shoulders": [
        "Cable Rope Upright Row",
        "Dumbbell Arnold Press",
        "Dumbbell Shoulder Press",
        "Dumbbell Shrugs",
        "Face Pull",
        "Front Raise",
        "Lateral Raise",
        "Rear Delt Fly",
    ],
    "Biceps": [
        "Small Barbell Curl",
        "Bicep Curl on Cable",
        "Bicep Preacher Curl",
        "Chin Up",
        "Dumbbell Bicep Curl",
        "Dumbbell Hammer Curl",
        "Hammer Curl on Cable",
        "Reverse Curl on Cable",
    ],
    "Triceps": [
        "Assisted Dips",
        "Cable Overhead Tricep Extension",
        "Dumbbell Overhead Tricep Extension",
        "Tricep Pushdown",
    ],
    "Legs": [
        "45 Degree Leg Press",
        "Barbell Squat",
        "Bodyweight Calf Raise",
        "Bodyweight Squat",
        "Bulgarian Split Squat",
        "Calf Raise",
        "Glute Kickback Machine",
        "Goblet Squat",
        "Hamstring Curl",
        "Hip Abduction Machine",
        "Hip Thrust",
        "Horizontal Leg Press",
        "Kettlebell Swing",
        "Leg Extension",
        "Sumo Squat",
        "Weighted Lunge",
    ],
    "Core": [
        "Bodyweight Abs Crunch",
        "Decline Bench Situp",
        "Hanging Knee Raise",
        "Leg Raise",
        "Plank Oblique Crunch",
        "Seated Abs Crunch Machine",
        "Situps",
    ],
}

EXERCISE_DEFAULT_EQUIPMENT = {
    "45 Degree Leg Press": "machine",
    "45 Degree T Bar Row": "machine",
    "Assisted Dips": "machine",
    "Assisted Pull Up": "machine",
    "Barbell Bench Press": "barbell",
    "Small Barbell Curl": "barbell",
    "Barbell Romanian Deadlift": "barbell",
    "Barbell Squat": "barbell",
    "Back Extension": "bodyweight",
    "Bicep Curl on Cable": "cable",
    "Bicep Preacher Curl": "machine",
    "Bodyweight Abs Crunch": "bodyweight",
    "Bodyweight Calf Raise": "bodyweight",
    "Bodyweight Squat": "bodyweight",
    "Bulgarian Split Squat": "dumbbells",
    "Cable Overhead Tricep Extension": "cable",
    "Cable Rope Upright Row": "cable",
    "Calf Raise": "machine",
    "Chest Supported Rows": "machine",
    "Chin Up": "bodyweight",
    "Compound Row Machine": "machine",
    "Dumbbell Arnold Press": "dumbbells",
    "Dumbbell Bench Press": "dumbbells",
    "Dumbbell Bicep Curl": "dumbbells",
    "Dumbbell Hammer Curl": "dumbbells",
    "Dumbbell Overhead Tricep Extension": "dumbbells",
    "Dumbbell Pec Fly": "dumbbells",
    "Dumbbell Romanian Deadlift": "dumbbells",
    "Dumbbell Rows": "dumbbells",
    "Dumbbell Shoulder Press": "dumbbells",
    "Dumbbell Shrugs": "dumbbells",
    "Decline Bench Situp": "bodyweight",
    "Face Pull": "cable",
    "Front Raise": "dumbbells",
    "Glute Kickback Machine": "machine",
    "Goblet Squat": "dumbbells",
    "Hamstring Curl": "machine",
    "Hammer Curl on Cable": "cable",
    "Hanging Knee Raise": "bodyweight",
    "Hip Abduction Machine": "machine",
    "Hip Thrust": "other",
    "Horizontal Leg Press": "machine",
    "Kettlebell Swing": "kettlebell",
    "Lat Pull Down": "machine",
    "Lateral Raise": "dumbbells",
    "Leg Extension": "machine",
    "Leg Raise": "bodyweight",
    "Pec Fly": "machine",
    "Plank Oblique Crunch": "bodyweight",
    "Pull Up": "bodyweight",
    "Push Up": "bodyweight",
    "Rear Delt Fly": "machine",
    "Reverse Curl on Cable": "cable",
    "Seated Abs Crunch Machine": "machine",
    "Seated Cable Row": "machine",
    "Single Arm Dumbbell Row": "dumbbells",
    "Situps": "bodyweight",
    "Straight Arm Cable Pulldown": "cable",
    "Sumo Squat": "dumbbells",
    "Tricep Pushdown": "cable",
    "Vertical Chest Press Machine": "machine",
    "Weighted Lunge": "dumbbells",
}
EXERCISE_DEFAULT_BODY_PART = {
    exercise: group
    for group, exercises in EXERCISE_GROUPS.items()
    for exercise in exercises
}
EXERCISE_DEFAULT_PER_HAND = frozenset({
    "Dumbbell Arnold Press",
    "Dumbbell Bench Press",
    "Dumbbell Bicep Curl",
    "Dumbbell Hammer Curl",
    "Dumbbell Pec Fly",
    "Dumbbell Rows",
    "Dumbbell Shoulder Press",
    "Dumbbell Shrugs",
    "Front Raise",
    "Lateral Raise",
    "Weighted Lunge",
})

VARIATION_CHOICES = ["default", "flat", "incline", "decline", "short grip", "wide grip", "reverse grip"]
BODY_FOCUS_CHOICES = [
    ("", "blank"),
    ("Back,Biceps", "Back + Biceps"),
    ("Chest,Triceps", "Chest + Triceps"),
    ("Legs", "Legs"),
    ("Shoulders,Core", "Shoulders + Abs"),
]
EQUIPMENT_CHOICES = [
    "",
    "bodyweight",
    "dumbbells",
    "barbell",
    "machine",
    "cable",
    "kettlebell",
    "smith machine",
    "band",
    "other",
]
BODY_PART_CHOICES = [""] + BODY_PART_ORDER
LOG_ROW_COUNT = 6
